### PR TITLE
fix: rwd redirect needs /learn prefix

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
I do not know how to test this, but it looks about right to me 👍

**Comment by moT01** [comment]
Will this take languages into account?

**Comment by raisedadead** [comment]
What just happened here? Is this a follow-up PR? Why was #88 merged earlier, I was going to test it out on staging.

**Comment by naomi-lgbt** [comment]
> What just happened here? Is this a follow-up PR?

Yes. I mistakenly thought that the `/learn` prefix was not necessary in the redirect.

> Why was https://github.com/freeCodeCamp/nginx-config/pull/88 merged earlier

I do not know.

**Comment by raisedadead** [comment]
I figured it out. @Sembauke dismissed the review prematurely.

I have since enabled the following:

image

This should prevent accidental abuse of the powers of the infinity stone Sem has! Lol.

**Comment by ojeytonwilliams** [comment]
> Will this take languages into account?

No, but no less than the other redirects. See, https://www.freecodecamp.org/espanol/about for example.

@raisedadead is this something that will be addressed in the current set of infra updates?

**Comment by raisedadead** [comment]
> is this something that will be addressed in the current set of infra updates?

Nope, at some point, all learn platform routing will be managed by the "server" that serves learn. I do intend to decouple and collocate app routing. Our L7 routing is ugly, and I very much intend to fix that.

Until then issues like this and https://github.com/freeCodeCamp/freeCodeCamp/issues/44818 and others are in limbo.

**Comment by ojeytonwilliams** [comment]
Okay, thanks for confirming.

**Comment by Sembauke** [comment]
@raisedadead whoops, my bad.

also: All abide to my powers

**Pull request merged**
