### PR TITLE
feat: add redirect for legacy RWD projects

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Should merge and deploy in tandem with https://github.com/freeCodeCamp/freeCodeCamp/pull/50960.

@raisedadead I hope I did this right? It should redirect: 

```txt
/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page
/learn/2022/responsive-web-design/build-a-tribute-page-project/build-a-tribute-page
``` 

for example.

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
I would start with a 302 first. It is easy to screw these things up. The code looks OK to me. I will test and confirm.

**Review by ojeytonwilliams — APPROVED** [review]
We should consolidate this stuff (let NGINX handle all redirects?), since our current approach of having at least three things(NGINX, serve and the client itself) responsible for redirection is just needlessly messy.
 
 Anyways, the logic looks good!

**Comment by raisedadead** [comment]
If I understand correctly, you want this to be deployed after the PR on main repo is deployed. Correct?

**Comment by naomi-lgbt** [comment]
Correct. In theory nothing would break if this was deployed earlier, but it would be confusing for anyone who happened to be going through the legacy RWD.

**Pull request merged**
