### PR TITLE
feat: add forum to news redirects

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
This PR adds redirects for 21 articles to see how traffic and SEO are affected by moving some of the most popular forum posts to /news.

### CODE REVIEW

**Comment by raisedadead** [comment]
Its my understanding that we will need to manage this redirection on the forum itself as well like we do for Ghost, because of its internal routing.

**Comment by raisedadead** [comment]
Can we revisit these?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, so sorry, I missed this notification. Yes, let's close this and try to handle it on the forum itself.

**Comment by raisedadead** [comment]
I think the point was missed, we still need to handle the redirects on the NGINX as the primary way to intercept these routes and add client side rounting on the forum as a fallback for the internal navigation.

**Pull request closed without merging**
