### PR TITLE
refactor: move enabled to available

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
This is more conventional. Rather than having everything enabled by default this helps us use the same config everywhere, but only turn on what's needed.

### CODE REVIEW

**Comment by raisedadead** [comment]
IMHO, its simpler to load all the config (its pretty cheap) onto the process memory, and manage pointing the domains via DNS, than trying to manage "enabled" config on various instances.

Because the VMs are ephimeral in nature and with the change that this PR introduces we will be breaking the fool-proofness of the version control. 

At the moment, we can pull down this repo and get NGINX serving traffic, as soon as we point the DNS to it, which itself is pretty fast thanks to CF.

I understand this is not conventional, but we are knowingly sacrificing that for fool-proofness.

**Comment by ojeytonwilliams** [comment]
That makes sense - I assume there's no noticeable performance hit from having one monolithic server rather than multiple dedicated ones. 

It does seem a little weird to involve CF directly in the proxying, though.  It feels like, particularly if we move to Terraform, that we'd want to handle that at the VM level rather than DNS.

**Comment by raisedadead** [comment]
> I assume there's no noticeable performance hit from having one monolithic server rather than multiple dedicated ones.

Well, it's more like one monolithic config - thanks to us using either a subdomain or a sub-directory. Each NGINX instance itself can be allotted to serve only part of the traffic. At the minute we happen to load balance and serve stuff from redundant instances. 

We can always map DNS entries to dedicated instances to parts (only subdomains) of the 'freecodecamp.org' TLD.

> It does seem a little weird to involve CF directly in the proxying, though.

CF is our CDN, and happens to be doing DNS as well. It doesn't do any proxying. Proxying happens at NGINX levels (which happen to be hosted VMS, they could be something else like containers). All (and literally all) reqs hit the NGINX instances, and may or may not be served from CF depending on the case / config.

**Comment by ojeytonwilliams** [comment]
Proxying wasn't right, sorry.  I was thinking about this:

> At the moment, we can pull down this repo and get NGINX serving traffic, as soon as we point the DNS to it, which itself is pretty fast thanks to CF.

So, right now we enable/disable servers via

```
if (-f /etc/nginx/maintenance/SERVER.txt) {
  return 503;
}
```

so, we could do similar things via `sites-enabled` which does basically the same thing, but in a different way.  Is your thinking that current way of doing it works, so why change?

**Comment by raisedadead** [comment]
Yes - because NGINX does not care about what directories we keep the files in. At the end of the day its a big nginx.conf file - one single scoped block of configuration. Conventionally its split into files and included using the `include` directive in the main nginx.conf file.

**Pull request closed without merging**
