### PR TITLE
feat: do not redirect if key is on a block list

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
@raisedadead before I dive too deeply into the NGINX rabbit hole, is a simple 403 error code enough?

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
I would want to avoid an `if` block if possible. I think for the intent of the PR a simple response [similar to this](https://github.com/freeCodeCamp/nginx-config/blob/c7ab30fd102f2de7e59a71706084fb1c138f2161/sites-enabled/10-www.freecodecamp.org.conf#L58-L62) should suffice.

Yes - the error code should be a 403

**Comment by ojeytonwilliams** [comment]
I think `if` is necessary, because `location` just matches the path.

Here's a discussion:
https://serverfault.com/questions/811912/can-nginx-location-blocks-match-a-url-query-string

All the approaches used `if` in various ways.

**Comment by raisedadead** [comment]
Thanks - I will defer to your best judgement.

**Comment by ojeytonwilliams** [comment]
I think this is fine, as long as you're happy with it just returning a 403 (explicit error pages are possible, but if the status code is enough, let's just do that).

Is the key you shared in chat the only one we need to block?  If so, I'll edit it in for testing on .dev

**Comment by raisedadead** [comment]
Yup, all I care about is the noise in the Ghost logs right now. This should do that.

> Is the key you shared in chat the only one we need to block? If so, I'll edit it in for testing on .dev

Yes.

**Comment by ojeytonwilliams** [comment]
Cool, if you wanna test this out on .dev it should be Just Work.

**Comment by ojeytonwilliams** [comment]
@raisedadead do you still want this in or can we close this?

**Pull request closed without merging**
