### PR TITLE
fix(news): proxy to JAMStack apps

### PR DESCRIPTION
**Pull request by raisedadead**
Closes https://github.com/freeCodeCamp/news/issues/76

### CODE REVIEW

**Comment by raisedadead** [comment]
Please review. NOT to be merged until deployment is tested.

**Review by nhcarrigan — APPROVED** [review]

**Review by ShaunSHamilton — COMMENTED** [review]
Just because I notice it:

Why does english not need the forwardslash:

https://github.com/freeCodeCamp/nginx-config/pull/49/files#diff-e9a6eaabf02311de962e74929647d25f2d7c22c778e533689599672b077d9d6aL72

**Comment by raisedadead** [comment]
> Why does english not need the forwardslash:

That link doesn't work for me. Do you mind posting a screenshot of the lines?

**Comment by ShaunSHamilton** [comment]
Sorry about that:
https://github.com/freeCodeCamp/nginx-config/blob/c7ab30fd102f2de7e59a71706084fb1c138f2161/sites-enabled/10-www.freecodecamp.org.conf#L67-L74

**Comment by raisedadead** [comment]
Thanks for adding the snippet. 

Yes - good question, it's because we need to push everything else that is NOT defined in the configs to somewhere, and this bit takes care to do that for us. Think of it as a catch-all. At least that's how I understand it. But I am no expert, maybe @ojeytonwilliams know better.

**Comment by ojeytonwilliams** [comment]
> If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:
location /name/ {
    proxy_pass http://127.0.0.1/remote/;
}

From the NGINX docs. With English, there's only a `/` which would get replaced by `/` so it should not matter.

**Comment by ojeytonwilliams** [comment]
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass explains it, but it's not the clearest.

**Pull request merged**
