### PR TITLE
fix: redirect spanish to espanol

### PR DESCRIPTION
**Pull request by ahmadabdolsaheb**

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]
LGTM. 

Before deploying, we would need to change a username `spanish` that just so happens to exist on the user records.

We would need to send the user a heads up that we are changing it to something like `spanish-user` and they are free to change it to anything else that they wish to other than `spanish` of course.

Also, we would want to expand the blocked list of the usernames.

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM, too.

I can change that person's username and send them an email. I'll also make a PR to add "spanish" and "espanol" to the blocked usernames list.

**Comment by raisedadead** [comment]
Thanks @scissorsneedfoodtoo, once you do - please merge and deploy this.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sure, sounds good. Just posted a PR. Will merge and deploy this once that gets merged.

**Comment by RandellDawson** [comment]
Why are we using `espanol` instead of `spanish`?  `Spanish` is the English spelling.  Does this mean we would use `francais` instead of `french` or `deutsche` instead of `german`.  Also, I  notice in other places we are using `es` instead of `espanol`.  I think we need to standardize across the entire repo and decide if we are going to using the English spelling of the languages or not.

**Pull request merged**
